pipeline:
  name: 建木官网CDN CI/CD
  ref: jianmu_official_site_cdn_cicd
  description: 建木官网CDN CI/CD
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-official-site.git
      ref: refs/heads/master
      netrc_machine: gitee.com
      netrc_username: ((gitee.username))
      netrc_password: ((gitee.password))
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone.git_path}
      build_arg: --mode cdn
  qiniu_upload:
    type: qiniu_upload:1.0.2
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${node_build.package_name}/${node_build.package_version}
      qiniu_upload_dir: ${git_clone.git_path}/dist
  update_index_page:
    type: scp_resouce:1.0.0
    param:
      ssh_private_key: ((private_key.alixg))
      ssh_ip: 47.243.164.48
      remote_file: /etc/nginx/html/index.html
      local_file: ${git_clone.git_path}/dist/index.html
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木官网CDN更新完成\\n\\n版本：${node_build.package_version}"
      msgtype: "text"
      mentioned_list: "[]"
